---

- name: Create /etc/iptables.rules
  template:
    src: 'iptables.rules.j2'
    dest: '/etc/iptables.rules'
    owner: root
    group: root
    mode: 0644

- name: Configure internal interface
  template:
    src: 'internal.conf.j2'
    dest: "/etc/network/interfaces.d/{{ internal_interface }}.conf"
    owner: root
    group: root
    mode: 0644

- name: Enable forwarding in sysctl config
  template:
    src: '60-ip-forward.conf.j2'
    dest: '/etc/sysctl.d/60-ip-forward.conf'
    owner: root
    group: root
    mode: 0644
